### ISSUE TITLE
Docs builds are failing on ReadTheDocs

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/sphinx-2i2c-theme#11]
### Context

Docs builds are failing on RTD. See 2i2c-org/infrastructure#1967 and 2i2c-org/infrastructure#1984 as recent examples. Logs can be seen here: https://readthedocs.org/projects/2i2c-pilot-hubs/builds/18870224/

Message is complaining about pyproject.toml and it looks like there may be a rogue double quote at the end of a version pin for sphinx-theme-builder, ~~but I can't actually see that dependency in our pyproject.toml file or anywhere in our repo? https://github.com/2i2c-org/infrastructure/search?q=sphinx-theme-builder~~

**Comment by choldgraf** [comment]
closed by #12
